export { default as Mouseclick } from './click.png'
export { default as flagen } from './003-united-states.png'
export { default as flagfr } from './005-flag-2.png'
export { default as flagvi } from './002-flag.png'
export { default as flagjp } from './001-japan.png'
export { default as flagcn } from './004-flag-1.png'
export { default as Vietnam } from './vietnammap.png'
export { default as Learn } from './knowledge.png'
export { default as Food } from './food (1).png'
export { default as Pho } from './Pho.jpg'